### ISSUE TITLE
GPL-920 BioSero Integration - EPIC to track progress of tasks [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/lighthouse#275]
**Description**
Requirements gathering, documentation and task tracking EPIC for the new BioSero systems. This includes the User requirements specification documentation (URS), process flow diagram, SATs documentation, central database documentation, and other minor tasks that need tracking.

**Who the primary contacts are for this work**
Rob Harkness (BioSero)
Lesley S
Scott T
Andrew S
Phil JV
Harriet C

**Knowledge or Stake holders**
Vernon J
Rich L
Ian J

**Requirements**

---
*DONE*
- [x] Change database schema and update stored procs, views and scripts to remove system_run_id, and createRunRecord sp to return the automation_system_run_id
- [x] Create central MySQL database server for Biosero (Live) - Requested from DBAs
- [x] Create database schema, views and stored procs in UAT - Requested from DBAs
- [x] Decide on a name for database and microservice - CherryTrack
- [x] Volume test common queries
- [x] MySQL - create Stored Procedures
- [x] MySQL - create script to add test data for volume testing
- [x] Create story for microservice [@emr @harrietc52 ]
- [x] Start API implementation stories in Lighthouse [@emrojo]
- [x] Review FAT and SAT docs from Biosero [all]
- [x] Update MySQL schema after DBAs feedback [@andrewsparkes ]
- [x] Revise and release v2.3 of URS and process diagram with central database changes (21/5)
- [x] Revise and release v1.1 of SAT with checks for database changes (21/5)
- [x] Release DB schema repo to Biosero (21/5)
- [x] Release initial Postman mocked version of Lighthouse API to Biosero (Rob H) (21/5)
- [x] Discuss schema design and performance with DBAs (24/5)
- [x] Revise stories backlog given central database and API changes
- [x] Create initial User Requirements Google Document
- [x] and distribute it
- [x] Create Biosero process flow diagram
- [x] Create Biosero SATs testing document
- [x] Create Hamilton SATs testing document (R&D)
- [x] Create architecture diagram
- [x] Create central MySQL database server for Biosero (UAT)
- [x] Design central database tables
- [x] Create DB schema repo in Github

**Additional context or information**
The BioSero systems will have some additional functionality around picking from consolidated plates that the Beckman systems do not have. e.g. The Hamilton liquid handlers have a 96-tip head for 'stamp' transfers as well as 8-channel pipetting capability like the Beckmans.

**Comment by andrewsparkes** [comment]
Meeting 18th 10am with Rob Harkness
Agreed to put together a Sanger Use Case document to describe the various scenarios we'd like the BioSero systems to handle (including handling consolidated plates as 1:1 picks, selective picking of important samples, algorithm-based partial picking of consolidated plates etc.)

**Comment by andrewsparkes** [comment]
Re-opening to track tasks to do
